/*
 * WeldingDataBase_v2.java
 *
 * Created on __DATE__, __TIME__
 */

package com.gy.frontFrame;

import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.JFrame;

import org.springframework.util.StringUtils;

import com.alibaba.fastjson.JSONObject;
import com.gy.login.PublicStaticSta;
import com.gy.user.entity.RecordEntity;
import com.gy.utils.date.DateChooser;
import com.gy.utils.http.HttpUtils;

/**
 *
 * @author  __USER__
 */
public class WeldingDataBase_v2 extends javax.swing.JFrame {

	/** Creates new form WeldingDataBase_v2 */
	public WeldingDataBase_v2() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jDesktopPane2 = new javax.swing.JDesktopPane();
		jLabel6 = new javax.swing.JLabel();
		jSeparator3 = new javax.swing.JSeparator();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		ssas = new javax.swing.JLabel();
		endDate = new javax.swing.JFormattedTextField();
		startDate = new javax.swing.JFormattedTextField();
		jSeparator7 = new javax.swing.JSeparator();
		jSeparator4 = new javax.swing.JSeparator();
		jSeparator1 = new javax.swing.JSeparator();
		responsePerson = new javax.swing.JFormattedTextField();
		recordName = new javax.swing.JFormattedTextField();
		classifyId = new javax.swing.JComboBox();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel10 = new javax.swing.JLabel();
		level = new javax.swing.JComboBox();
		jLabel11 = new javax.swing.JLabel();
		storeDate = new javax.swing.JComboBox();
		jSeparator2 = new javax.swing.JSeparator();
		jLabel12 = new javax.swing.JLabel();
		recordId = new javax.swing.JFormattedTextField();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jDesktopPane2.setBackground(new java.awt.Color(255, 255, 255));
		jDesktopPane2.setAutoscrolls(true);

		jLabel6.setFont(new java.awt.Font("新宋体", 1, 18));
		jLabel6.setText("\u5206\u7c7b");
		jLabel6.setBounds(570, 60, 90, 30);
		jDesktopPane2.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jSeparator3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jSeparator3MouseClicked(evt);
			}
		});
		jSeparator3.setBounds(100, 200, 1310, 20);
		jDesktopPane2.add(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel7.setFont(new java.awt.Font("新宋体", 1, 18));
		jLabel7.setText("\u67e5\u8be2\u6761\u4ef6");
		jLabel7.setBounds(100, 20, 90, 30);
		jDesktopPane2.add(jLabel7, javax.swing.JLayeredPane.PALETTE_LAYER);

		jLabel8.setFont(new java.awt.Font("新宋体", 1, 18));
		jLabel8.setText("\u65e5\u671f");
		jLabel8.setBounds(100, 60, 90, 30);
		jDesktopPane2.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel9.setFont(new java.awt.Font("新宋体", 1, 18));
		jLabel9.setText("\u9898\u540d");
		jLabel9.setBounds(100, 160, 90, 30);
		jDesktopPane2.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

		ssas.setFont(new java.awt.Font("新宋体", 1, 18));
		ssas.setText("\u8d23\u4efb\u8005");
		ssas.setBounds(570, 110, 80, 30);
		jDesktopPane2.add(ssas, javax.swing.JLayeredPane.DEFAULT_LAYER);

		endDate.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1,
				1, new java.awt.Color(204, 0, 0)));
		endDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		endDate.setText("\u7ec8\u6b62\u65e5\u671f");
		endDate.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				endDateMouseClicked(evt);
			}
		});
		endDate.setBounds(390, 60, 90, 30);
		jDesktopPane2.add(endDate, javax.swing.JLayeredPane.DEFAULT_LAYER);

		startDate.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1,
				1, 1, new java.awt.Color(255, 0, 0)));
		startDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		startDate.setText("\u8d77\u59cb\u65e5\u671f");
		startDate.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				startDateMouseClicked(evt);
			}
		});
		startDate.setBounds(200, 60, 90, 30);
		jDesktopPane2.add(startDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jSeparator7.setBounds(310, 70, 60, 20);
		jDesktopPane2.add(jSeparator7, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jSeparator4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jSeparator4MouseClicked(evt);
			}
		});
		jSeparator4.setBounds(100, 50, 1310, 20);
		jDesktopPane2.add(jSeparator4, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
		jSeparator1.setBounds(990, 60, 30, 100);
		jDesktopPane2.add(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
		responsePerson.setBounds(680, 110, 270, 30);
		jDesktopPane2.add(responsePerson,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		recordName.setBounds(200, 160, 280, 30);
		jDesktopPane2.add(recordName, javax.swing.JLayeredPane.DEFAULT_LAYER);

		classifyId.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"", "焊材", "焊接工艺"}));
		classifyId.setBounds(680, 60, 270, 30);
		jDesktopPane2.add(classifyId, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null } },
				new String[] { "Title 1", "Title 2", "Title 3", "Title 4",
						"Title 5", "Title 6", "Title 7" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false,
					false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jTable1.setRequestFocusEnabled(false);
		jTable1.setRowHeight(25);
		jScrollPane1.setViewportView(jTable1);

		jScrollPane1.setBounds(100, 210, 1320, 550);
		jDesktopPane2.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel10.setFont(new java.awt.Font("新宋体", 1, 18));
		jLabel10.setText("\u5bc6\u7ea7");
		jLabel10.setBounds(1040, 60, 90, 30);
		jDesktopPane2.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

		level.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"", "秘密", "一般" }));
		level.setBounds(1140, 60, 270, 30);
		jDesktopPane2.add(level, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel11.setFont(new java.awt.Font("新宋体", 1, 18));
		jLabel11.setText("\u4fdd\u7ba1\u671f\u9650");
		jLabel11.setBounds(1040, 110, 90, 30);
		jDesktopPane2.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

		storeDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"", "长期", "永久"}));
		storeDate.setBounds(1140, 110, 270, 30);
		jDesktopPane2.add(storeDate, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
		jSeparator2.setBounds(520, 60, 30, 120);
		jDesktopPane2.add(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel12.setFont(new java.awt.Font("新宋体", 1, 18));
		jLabel12.setText("\u6863\u6848\u53f7");
		jLabel12.setBounds(100, 110, 90, 30);
		jDesktopPane2.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
		recordId.setBounds(200, 110, 280, 30);
		jDesktopPane2.add(recordId, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jMenu1.setText("\u710a\u63a5\u6240\u5386\u53f2");
		jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jMenu1MouseClicked(evt);
			}
		});

		jMenuItem1.setText("91--92");
		jMenu1.add(jMenuItem1);

		jMenuBar1.add(jMenu1);

		jMenu2.setText("\u6570\u636e\u5e93\u67e5\u8be2");
		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jDesktopPane2,
								javax.swing.GroupLayout.DEFAULT_SIZE, 1504,
								Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addComponent(jDesktopPane2,
								javax.swing.GroupLayout.PREFERRED_SIZE, 881,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(83, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {

		Frame[] frames = WeldingDataBase_v2.getFrames();
		Boolean flag = false;
		for (Frame frame : frames) {
			if (frame.getName().equals("WeldingDataBase_v2")) {
				flag = true;
			}
		}
		if (!flag) {
			this.dispose();
			new MainFrame().setVisible(true);
		}
	}

	private void jSeparator4MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
	}

	private void startDateMouseClicked(java.awt.event.MouseEvent evt) {
		final JFrame frame = new JFrame("起始日期选择");
		frame.setSize(400, 300);

		final DateChooser datePicker = new DateChooser();
		datePicker.addActionListener(new ActionListener() {// 事件捕获

					public void actionPerformed(ActionEvent e) {
						startDate.setValue(datePicker.getSelectedDate());
						frame.setVisible(false);
					}
				});
		frame.getContentPane().add(datePicker);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setLocationRelativeTo(null);
		frame.setVisible(true);
	}

	private void endDateMouseClicked(java.awt.event.MouseEvent evt) {
		final JFrame frame = new JFrame("起始日期选择");
		frame.setSize(400, 300);

		final DateChooser datePicker = new DateChooser();
		datePicker.addActionListener(new ActionListener() {// 事件捕获

					public void actionPerformed(ActionEvent e) {
						endDate.setValue(datePicker.getSelectedDate());
						frame.setVisible(false);
						search();
					}

				});
		frame.getContentPane().add(datePicker);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setLocationRelativeTo(null);
		frame.setVisible(true);
	}

	private void jSeparator3MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new WeldingDataBase_v2().setVisible(true);
			}
		});
	}

	//搜索使用
	private void search() {
		Map<String, String> map = new HashMap();

		//日期
		handleParameters(map);

		String token = PublicStaticSta.getinstance().getStatus();
		map.put("token", token);
		try {
			String postForm = HttpUtils.postForm(
					"http://localhost:8080/findRecordEntity", map);
			List<RecordEntity> recordEntityList =(List<RecordEntity>) JSONObject.parse(postForm);
			changeTableData(recordEntityList);
			System.out.println();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void changeTableData(List<RecordEntity> recordEntityList) {
		Object[][] recordList = new Object[0][];
		for (int i = 0; i < recordEntityList.size()-1; i++) {
			RecordEntity recordEntity = recordEntityList.get(i);
			recordList[i][0] = recordEntity.getRecordId();
			recordList[i][1] = recordEntity.getRecordName();
			recordList[i][2] = recordEntity.getRecordDate();
			recordList[i][3] = recordEntity.getRecordStoreDate();
			recordList[i][4] = recordEntity.getLevel();
			recordList[i][5] = recordEntity.getResponsePerson();
			recordList[i][6] = recordEntity.getClassifyName();
		}
		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				recordList,
				new String[] { "RecordId", "RecordName", "RecordDate", "RecordStoreDate",
						"Level", "ResponsePerson", "ClassifyName" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false,
					false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
	}

	private void handleParameters(Map<String, String> map) {
		String startDateStr = (String) startDate.getValue();
		String endDateStr = (String) endDate.getValue();
		Date startDate = null;
		Date endDate = null;
		if (startDateStr != null && endDateStr != null) {
			startDate = transDate(startDateStr);
			endDate = transDate(endDateStr);
			map.put("startDate", startDate.toString());
			map.put("endDate", endDate.toString());
		}
		//分类
		//关键词search
		String name = (String) recordName.getText();
		String responsePersonStr = (String) responsePerson.getText();
		String recordIdStr = (String) recordId.getText();
		String classifyIdStr = classifyId.getSelectedItem().toString();
		String levelStr = level.getSelectedItem().toString();
		String storeDateStr = storeDate.getSelectedItem().toString();
		if (!StringUtils.isEmpty(name)) {
			map.put("recordName", name);
		}
		if (!StringUtils.isEmpty(responsePersonStr)) {
			map.put("responsePerson", responsePersonStr);
		}
		if (!StringUtils.isEmpty(recordIdStr)) {
			map.put("recordId", recordIdStr);
		}
		if (!StringUtils.isEmpty(classifyIdStr)) {
			map.put("classifyId", classifyIdStr);
		}
		if (!StringUtils.isEmpty(levelStr)) {
			map.put("level", null);
		}
		if (!StringUtils.isEmpty(storeDateStr)) {
			map.put("storeDate", storeDateStr);
		}
	}

	private Date transDate(String startDateStr) {
		DateFormat df = new SimpleDateFormat("dd-MM-yyyy");
		Date date = null;
		try {
			date = df.parse(startDateStr);
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return date;
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JComboBox classifyId;
	private javax.swing.JFormattedTextField endDate;
	private javax.swing.JDesktopPane jDesktopPane2;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JSeparator jSeparator3;
	private javax.swing.JSeparator jSeparator4;
	private javax.swing.JSeparator jSeparator7;
	private javax.swing.JTable jTable1;
	private javax.swing.JComboBox level;
	private javax.swing.JFormattedTextField recordId;
	private javax.swing.JFormattedTextField recordName;
	private javax.swing.JFormattedTextField responsePerson;
	private javax.swing.JLabel ssas;
	private javax.swing.JFormattedTextField startDate;
	private javax.swing.JComboBox storeDate;
	// End of variables declaration//GEN-END:variables

}